# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # using major version aliases

  # aliased to a recent 5.3.x version
  - 5.3

  # aliased to a recent 5.4.x version
  - 5.4

# optionally specify a list of environments, for example to test different RDBMS
env:
  - DB=mysql

before_install:
  - "git submodule update --init --recursive"


# whitelist
branches:
  only:
    - master

# configure notifications (email, IRC, campfire etc)
notifications:
  irc:
    channels:
      - "irc.freenode.org#gleez"
    template:
      - "%{repository}/%{branch} (%{commit}) - %{author}: %{message}"
      - "Build details: %{build_url}"
  email: false